AWSTemplateFormatVersion: '2010-09-09'
Description: Restaurant Microservice Deployment on ECS

Resources:

  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: RestaurantServiceCluster

  # Task Definition for Restaurant Service
  RestaurantServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: restaurant-service
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: restaurant-service
          Image: 529088288756.dkr.ecr.us-west-1.amazonaws.com/restaurant-service:latest
          PortMappings:
            - ContainerPort: 5004
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/restaurant-service
              awslogs-region: us-west-1
              awslogs-stream-prefix: ecs

  # ECS Service
  RestaurantService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref RestaurantServiceTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-0d7c244183aa6bdb3 # Replace with actual subnet IDs
            - subnet-0f82aeca842b791d5
          SecurityGroups:
            - !Ref RestaurantServiceSecurityGroup
          AssignPublicIp: ENABLED

  # Security Group for Restaurant Service
  RestaurantServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to restaurant-service
      VpcId: vpc-03babb770cac46467 # Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5004
          ToPort: 5004
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # IAM Role for ECS Task Execution
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
